export const imgData = [
    {
        "id": 1,
        "tags": "spring",
        "src": "./images/spring1.jpg",
        "height": "300px",
        "width": "200px",


    },
    {
        "id": 2,
        "tags": "spring",
        "src": "./images/spring2.jpeg",
        "height": "200px",
        "width": "200px",
    },
    {
        "id": 3,
        "tags": "spring",
        "src": "./images/spring3.jpg",
        "height": "232px",
        "width": "200px",
    },
    {
        "id": 4,
        "tags": "spring",
        "src": "./images/spring4.jpg",
        "height": "300px",
        "width": "450px",
    },
    {
        "id": 5,
        "tags": "spring",
        "src": "./images/spring5.jpg",
        "height": "480px",
        "width": "398px",
    },
    {
        "id": 6,
        "tags": "summer",
        "src": "./images/summer1.jpg",
        "height": "650px",
        "width": "200px",
    },
    {
        "id": 7,
        "tags": "summer",
        "src": "./images/summer2.jpg",
        "height": "345px",
        "width": "200px",
    },
    {
        "id": 8,
        "tags": "summer",
        "src": "./images/summer3.jpg",
        "height": "369px",
        "width": "200px",
    },
    {
        "id": 9,
        "tags": "summer",
        "src": "./images/summer4.jpg",
        "height": "501px",
        "width": "578px",
    },
    {
        "id": 10,
        "tags": "summer",
        "src": "./images/summer5.jpg",
        "height": "300px",
        "width": "400px",
    },
    {
        "id": 11,
        "tags": "fall",
        "src": "./images/fall1.jpg",
        "height": "587px",
        "width": "651px",
    },
    {
        "id": 12,
        "tags": "fall",
        "src": "./images/fall2.jpg",
        "height": "300px",
        "width": "200px",
    },
    {
        "id": 13,
        "tags": "fall",
        "src": "./images/fall3.jpg",
        "height": "467px",
        "width": "200px",
    },
    {
        "id": 14,
        "tags": "fall",
        "src": "./images/fall4.jpg",
        "height": "287px",
        "width": "230px",
    },
    {
        "id": 15,
        "tags": "fall",
        "src": "./images/fall5.jpg",
        "height": "300px",
        "width": "164px",
    },
    {
        "id": 16,
        "tags": "winter",
        "src": "./images/winter1.jpg",
        "height": "632px",
        "width": "450px",
    },
    {
        "id": 17,
        "tags": "winter",
        "src": "./images/winter2.jpg",
        "height": "300px",
        "width": "200px",
    },
    {
        "id": 18,
        "tags": "winter",
        "src": "./images/winter3.jpg",
        "height": "150px",
        "width": "200px",
    },
    {
        "id": 19,
        "tags": "winter",
        "src": "./images/winter4.jpg",
        "height": "621px",
        "width": "578px",
    },
    {
        "id": 20,
        "tags": "winter",
        "src": "./images/winter5.jpg",
        "height": "598px",
        "width": "621px",
    },

]
